
default: &default
  adapter: postgresql
  encoding: unicode
  username: larbi
  password: railsdevpg22
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: shatta_development

test:
  <<: *default
  database: shatta_test

production:
  <<: *default
  database: shatta_production
  username: shatta
  password: <%= ENV["SHATTA_DATABASE_PASSWORD"] %>
